### ISSUE TITLE
Bgp neighbors not working

### ISSUE THREAD

**Issue by helpdeskdan** [napalm-automation-community/napalm-netiron#3]
<pre>
>>> device.open()
>>> device.get_bgp_neighbors()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/napalm_netiron/netiron.py", line 1478, in get_bgp_neighbors
    IPV4_ADDR_REGEX, IPV6_ADDR_REGEX, ASN_REGEX), line)
  File "/usr/lib/python3.7/re.py", line 173, in match
    return _compile(pattern, flags).match(string)
  File "/usr/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.7/sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.7/sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.7/sre_parse.py", line 813, in _parse
    source.tell() - start)
re.error: missing ), unterminated subpattern at position 4
>>>
</pre>

**Comment by helpdeskdan** [comment]
Sorry, I should have at least looked at it.  It's an easy fix:

<pre>
1476                 r'^\s+(?P<remote_addr>({}|{}))\s+(?P<remote_as>({}))\s+(?P<state>\S+)\s+'
</pre>
To bold that missing parenthesis: 
 r'^\s+(?P<remote_addr>({}|{})**)**\s+(?P<remote_as>({}))\s+(?P<state>\S+)\s+'

Some python3 fixes might be good - unicode for instance.  Thkx for the project work.

**Comment by helpdeskdan** [comment]
#*@&, rob has already fixed both - check the pull
